# Generated by Django 5.0.7 on 2024-07-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor_code',
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_barcode',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Штрих-код Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_fbo_sku_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ID SKU FBO Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_fbs_sku_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ID SKU FBS Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_product_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ID продукта Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozon_sku',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='SKU Ozon'),
        ),
        migrations.AddField(
            model_name='product',
            name='willberries_barcode',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Штрих-код Willberries'),
        ),
        migrations.AddField(
            model_name='product',
            name='willberries_vendor_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Артикул Willberries'),
        ),
        migrations.AddField(
            model_name='product',
            name='yandex_barcode',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Штрих-код Яндекс.Маркета'),
        ),
        migrations.AddField(
            model_name='product',
            name='yandex_sku',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='SKU Яндекс.Маркета'),
        ),
        migrations.AddField(
            model_name='product',
            name='yandex_vendor_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Артикул Яндекс.Маркета'),
        ),
    ]
