# Generated by Django 5.0.7 on 2024-08-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ozonproductsales',
            name='ozon',
        ),
        migrations.RemoveField(
            model_name='ozonproductsales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wildberriesproductsales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wildberriesproductsales',
            name='wildberries',
        ),
        migrations.RemoveField(
            model_name='yandexmarketproductsales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='yandexmarketproductsales',
            name='yandex_market',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('vendor_code',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ozon_barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ozon_fbo_sku_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ozon_fbs_sku_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ozon_product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ozon_vendor_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='place_in_warehouse',
        ),
        migrations.RemoveField(
            model_name='product',
            name='willberries_barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='willberries_vendor_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='yandex_barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='yandex_sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='yandex_vendor_code',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default='K7U', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ozon_sku',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('ozon_quantity', models.IntegerField(default=0)),
                ('wildberries_quantity', models.IntegerField(default=0)),
                ('yandex_market_quantity', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Product sale',
                'verbose_name_plural': 'Product sales',
                'db_table': 'product_sales',
                'ordering': ('product__vendor_code',),
                'unique_together': {('product', 'company', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='InProduction',
        ),
        migrations.DeleteModel(
            name='OzonProductSales',
        ),
        migrations.DeleteModel(
            name='WildberriesProductSales',
        ),
        migrations.DeleteModel(
            name='YandexMarketProductSales',
        ),
    ]
