# Generated by Django 5.0.8 on 2024-09-26 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='author_user',
            field=models.ManyToManyField(blank=True, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Author Users'),
        ),
    ]
