# Generated by Django 5.0.8 on 2024-08-26 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='ozon_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='wildberries_quantity',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='yandex_market_quantity',
        ),
        migrations.AddField(
            model_name='productstock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstock',
            name='marketplace_type',
            field=models.CharField(choices=[('wildberries', 'Wildberries'), ('ozon', 'Ozon'), ('yandexmarket', 'YandexMarket')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
