# Generated by Django 5.0.8 on 2024-08-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceservice', '0003_remove_yandexmarket_uuid_yandexmarket_id'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='ozon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplaceservice.ozon'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='wildberries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplaceservice.wildberries'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='yandexmarket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplaceservice.yandexmarket'),
        ),
    ]
