# Generated by Django 5.0.8 on 2024-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_ozon_quantity_productstock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='date',
            field=models.DateField(),
        ),
    ]
