# Generated by Django 5.0.8 on 2024-08-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productsale_ozon_alter_productsale_wildberries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='ozon',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='wildberries',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='yandexmarket',
        ),
    ]
