# Generated by Django 5.0.8 on 2024-08-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productsale_ozon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
