# Generated by Django 5.0.8 on 2024-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productstock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseForStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marketplace_type', models.CharField(choices=[('wildberries', 'Wildberries'), ('ozon', 'Ozon'), ('yandexmarket', 'YandexMarket')], max_length=50)),
            ],
        ),
    ]
