# Generated by Django 5.0.8 on 2024-08-28 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_warehouseforstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.warehouseforstock'),
        ),
    ]
