# Generated by Django 5.0.8 on 2024-08-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productsale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='ozon_quantity',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='wildberries_quantity',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='yandex_market_quantity',
        ),
    ]
