# Generated by Django 5.0.8 on 2024-08-30 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productstock_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ozon_sku',
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace_type',
            field=models.CharField(choices=[('wildberries', 'Wildberries'), ('ozon', 'Ozon'), ('yandexmarket', 'YandexMarket')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
