# Generated by Django 5.0.8 on 2024-08-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productsale_ozon_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('name', 'country_name', 'oblast_okrug_name', 'region_name', 'shelf')},
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='ozon_quantity',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='wildberries_quantity',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='yandex_market_quantity',
        ),
        migrations.AddField(
            model_name='productorder',
            name='marketplace_type',
            field=models.CharField(choices=[('wildberries', 'Wildberries'), ('ozon', 'Ozon'), ('yandexmarket', 'YandexMarket')], default='wildberries', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorder',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorder',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
