# Generated by Django 5.0.8 on 2024-09-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_ozon_sku_product_marketplace_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.CharField(max_length=20)),
                ('full_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('name', 'country_name', 'oblast_okrug_name', 'region_name')},
        ),
        migrations.CreateModel(
            name='WarehouseForCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.shelf')),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='shelf',
        ),
    ]
