# Generated by Django 5.0.8 on 2024-09-05 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companysettings'),
        ('product', '0007_shelf_alter_warehouse_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseforcompany',
            name='shelf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelOptions(
            name='warehouseforcompany',
            options={'ordering': ['stock'], 'verbose_name': 'Склад'},
        ),
        migrations.AddField(
            model_name='warehouseforcompany',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productsale',
            unique_together={('product', 'company', 'date', 'warehouse', 'marketplace_type')},
        ),
        migrations.AlterModelTable(
            name='warehouseforcompany',
            table='warehouse_for_company',
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
