# Generated by Django 5.0.8 on 2024-09-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_warehouseforcompany_shelf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marketplace_type',
        ),
    ]
