# Generated by Django 5.0.8 on 2024-09-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'Product stock', 'verbose_name_plural': 'Product stocks'},
        ),
    ]
