# Generated by Django 5.0.8 on 2024-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_recommendations_delete_warehouseforcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='succes_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
