# Generated by Django 5.0.8 on 2024-09-09 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_recommendations_succes_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='id',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
