# Generated by Django 5.0.8 on 2024-09-09 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_companysettings_sale_coefficient_and_more'),
        ('product', '0015_delete_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('succes_quantity', models.PositiveIntegerField()),
                ('days_left', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Рекомендации',
                'db_table': 'recommendations',
                'ordering': ['quantity'],
            },
        ),
    ]
