# Generated by Django 5.0.8 on 2024-09-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_recommendations_succes_quantity_inproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inproduction',
            name='recommendations',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.recommendations'),
            preserve_default=False,
        ),
    ]
