# Generated by Django 5.0.8 on 2024-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_sortingwarehouse_shelf_warhousehistory_shelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='succes_quantity',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='application_for_production',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
