# Generated by Django 5.0.8 on 2024-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_recommendations_succes_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warhousehistory',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
