# Generated by Django 5.0.8 on 2024-09-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_next_sale_days'),
        ('product', '0025_alter_warhousehistory_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WarhouseHistory',
            new_name='WarehouseHistory',
        ),
        migrations.AlterField(
            model_name='shelf',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
