# Generated by Django 5.0.8 on 2024-09-14 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_rename_warhousehistory_warehousehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inproduction',
            name='recommendations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.recommendations'),
        ),
    ]
