# Generated by Django 5.0.8 on 2024-09-24 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_next_sale_days'),
        ('product', '0032_alter_recommendations_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityShipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_days', models.IntegerField(default=0)),
                ('arrive_days', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('shipments', models.IntegerField(default=0)),
                ('sales_share', models.FloatField(default=0)),
                ('shipments_share', models.FloatField(default=0)),
                ('shipping_priority', models.FloatField(default=0)),
                ('marketplace_type', models.CharField(choices=[('wildberries', 'Wildberries'), ('ozon', 'Ozon'), ('yandexmarket', 'YandexMarket')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.warehouse')),
            ],
            options={
                'unique_together': {('company', 'warehouse')},
            },
        ),
    ]
