# Generated by Django 5.0.8 on 2024-09-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_next_sale_days'),
        ('product', '0035_shipment_shipmenthistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together={('recomamand_supplier', 'product', 'company')},
        ),
    ]
