# Generated by Django 5.0.8 on 2024-09-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_shipment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmenthistory',
            name='shipment',
        ),
    ]
