# Generated by Django 5.0.8 on 2024-10-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_next_sale_days'),
        ('product', '0037_remove_shipmenthistory_shipment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'company', 'date', 'warehouse', 'marketplace_type', 'quantity')},
        ),
    ]
