# Generated by Django 5.0.8 on 2024-10-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_productstock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendations',
            unique_together=set(),
        ),
    ]
