# Generated by Django 5.0.8 on 2024-10-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_inventory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_fact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recomamand_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.recomamandationsupplier'),
        ),
    ]
