# Generated by Django 5.0.3 on 2024-10-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_next_sale_days'),
        ('product', '0043_alter_shipment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('name', 'oblast_okrug_name')},
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'company', 'date', 'warehouse', 'marketplace_type')},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='region_name',
        ),
    ]

    
