# Generated by Django 5.0.3 on 2024-10-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_next_sale_days'),
        ('product', '0044_alter_warehouse_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claster_to', models.CharField(max_length=150)),
                ('region_name', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'unique_together': {('claster_to', 'region_name')},
            },
        ),
    ]
