# Generated by Django 5.0.3 on 2024-10-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_next_sale_days'),
        ('product', '0045_claster'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='claster',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='WarehouseYandex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.IntegerField()),
                ('claster_to', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
