# Generated by Django 5.0.8 on 2024-09-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_countp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountP',
        ),
    ]
