# Generated by Django 5.0.8 on 2024-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_companysettings_sale_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='next_sale_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
