# Generated by Django 5.0.7 on 2024-07-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ozon',
            fields=[
                ('uuid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('api_token', models.CharField(blank=True, max_length=1000, null=True, verbose_name='API токен Ozon')),
                ('client_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Клиентский ID Ozon')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OzonCompany', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Ozon',
                'verbose_name_plural': 'Ozon',
                'db_table': 'ozon_table',
            },
        ),
        migrations.CreateModel(
            name='Wildberries',
            fields=[
                ('uuid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('wb_api_key', models.CharField(blank=True, max_length=1000, null=True, verbose_name='API ключ Wildberries')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WildberriesCompany', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Wildberries',
                'verbose_name_plural': 'Wildberries',
                'db_table': 'wildberries_table',
            },
        ),
        migrations.CreateModel(
            name='YandexMarket',
            fields=[
                ('uuid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('api_key_bearer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='API ключ Bearer YandexMarket')),
                ('fby_campaign_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='FBS Кампания ID YandexMarket')),
                ('fbs_campaign_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='FBY Кампания ID YandexMarket')),
                ('business_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Бизнес ID YandexMarket')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='YandexMarketCompany', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'YandexMarket',
                'verbose_name_plural': 'YandexMarket',
                'db_table': 'yandexMarket_table',
            },
        ),
    ]
