# Generated by Django 5.0.7 on 2024-08-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozon',
            name='uuid',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
