# Generated by Django 5.0.8 on 2024-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceservice', '0002_alter_ozon_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yandexmarket',
            name='uuid',
        ),
        migrations.AddField(
            model_name='yandexmarket',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор'),
            preserve_default=False,
        ),
    ]
